[package]
name = "knowledge-key"
version = "1.0.0"
compiler = "0.11.0"
entrypoint = "lib.typ"
repository = "https://github.com/ngoetti/knowledge-key"
authors = ["Nick Goetti"]
license = "LGPL-2.1"
description = "A compact cheat-sheet"
keywords = ["cheat-sheet", "cheat", "sheet", "university"]
categories = ["flyer"]
disciplines = ["computer-science", "engineering"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
